ts_search_index:
    resource: "@TsSearchBundle/Controller/"
    type:     annotation
    prefix:   /
ts_search_deeplink:
    path:      /search/{url}
    defaults:  { _controller: TsSearchBundle:Search:search }